### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by charika1987** [DavidTorresOcana/image_pipeline#2]
I am having another issue with the tool. When I push the calibrate button, calibration is conducted and the undistorted image is displayed in the window. But the problem is the lines of the extracted checkerboard are not overlapping in the corresponding corners in the undistorted image. Do you have any input to this?
Kind regards
Charika

**Comment by DavidTorresOcana** [comment]
Hello

From my experience this is due to a bad calibration. Try to cover as many edges and corners as possible. 
Depending on the camera, you can also try by setting different flags to yield better results as suggested here: https://stackoverflow.com/questions/26794937/fisheye-lens-calibration-with-opencv-3-0

For this kind of questions, please use forums like StackOverflow. This is to cover features and bugs.

Regards
